// <auto-generated />
using Infra.Data.Contextos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infra.Data.Migrations
{
    [DbContext(typeof(MemoRizeContext))]
    [Migration("20200626124002_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dominios.Classes.Sessoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Errou")
                        .HasColumnName("Errou")
                        .HasColumnType("bit");

                    b.Property<int>("Fase")
                        .HasColumnName("Fase")
                        .HasColumnType("int");

                    b.Property<bool>("PassarDeFase")
                        .HasColumnName("PassarDeFase")
                        .HasColumnType("bit");

                    b.Property<string>("SequenciaCorreta")
                        .IsRequired()
                        .HasColumnName("SequenciaCorreta")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SequenciaRecebida")
                        .IsRequired()
                        .HasColumnName("SequenciaRecebida")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Sessao");
                });
#pragma warning restore 612, 618
        }
    }
}
